name: Deploy FastAPI AWS Starter Kit

on:
  push:
    branches: 
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '19.x'

    - name: Installing Serverless
      run: make install-serverless

    - name: Installing Python requirements
      run: make install-python-requirements

    - name: Black code analysis
      run: make black

    - name: Flake8 code analysis
      run: make flake8

    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy with Serverless
      run: make deploy